import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from "next/legacy/image"; // Import the Image component
import ziggs from '/src/app/assets/images/splash/ziggs-bg.jpg';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LOL AI Champ Creator',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Preload the image */}
      <link rel="preload" href={ziggs.src} as="image" />
      <body className={inter.className}>
        {/* Use the Image component to display the image */}
        <Image
          src={ziggs}
          alt="Ziggs Background"
          layout="fill" // Set layout to "fill" to preload the image
        />
        {children}
      </body>
    </html>
  );
}
