require('dotenv').config()

import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from "next/legacy/image"; 
import ziggs from './assets/images/splash/ziggs-bg.jpg';
import maokai from './assets/images/splash/maokai-splash.jpg';
import jax from './assets/images/splash/jax.jpg';
import koglulu from './assets/images/splash/kogmaw-lulu-splash.jpg';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LOL AI Champ Creator',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <link rel="preload" href={ziggs.src} as="image" /> */}
      <body className={inter.className}>
        <Image
          src={ziggs}
          alt="Ziggs Background"
          layout="fill"
          objectFit='cover'
        />
        {children}
      </body>
    </html>
  );
}
